### ISSUE TITLE
ErrInvalidRecipient is not returned from GetRecipientDetails() as documented

### ISSUE THREAD

**Issue by bconway** [gregdel/pushover#21]
It appears that this error is only defined, but never used?

https://github.com/gregdel/pushover/search?q=ErrInvalidRecipient

**Comment by PouuleT** [comment]
Hello @bconway !

You're right, this error is defined but never used ( it was in the past, but was forgotten during a refactor )
I fixed it here https://github.com/gregdel/pushover/pull/22 and updated the documentation

Thanks for the issue!
