### ISSUE TITLE
Crashes on timeout

### ISSUE THREAD

**Issue by 161134050** [gregdel/pushover#8]
```
go version go1.13 linux/amd64
go build
 ./main
2020/04/16 05:03:21 Post "https://api.pushover.net/1/messages.json": dial tcp 207.244.81.102:443: i/o timeout
panic: Post "https://api.pushover.net/1/messages.json": dial tcp 207.244.81.102:443: i/o timeout

goroutine 1 [running]:
log.Panic(0xc00010ff68, 0x1, 0x1)
    /usr/lib/go-1.14/src/log/log.go:351 +0xac
main.main()
    /home/runner/ImpoliteAdolescentTrust/main.go:22 +0xef
exit status 2
```

**Comment by gregdel** [comment]
Hello, are you using the code provided in the first example of the readme ? 

If that's the case:
* the `sendMessage` function returns an error stored in `err`
* `err` is therefore not `nil` on the next line
* the code explicitly panics with a `log.Panic()`

This is just an example, you should handle the error the properly depending on your need.
If you wish to only log the error, replace the `log.Panic` with `log.Print` and add a return statement after logging.

**Comment by 161134050** [comment]
Good point, I'll make my sendNotification function call its self recursively upon failure -thanks
